### ISSUE TITLE
Feature: Fantasy Football

### ISSUE THREAD

**Issue by DBH1986** [Mayple7/CorgiBot#11]
May be a separate bot or an enhancement to this one, but a FF bot could have a lot of useful items

- Making Picks
  - People could tell the bots what picks they make which could possibly auto update yahoo, or it could keep a list of currently available players for people to check.
  - People could query the bot for last season stats or the like in order to be informed to make picks
  - The bot could auto send pings to people when their draft position is coming up
- Reporting Scores and keeping stats
  - If we can plug into Yahoo the bot could automatically give final scores, keep track of records or even auto tabulate year long or multi-year stats.
- Trades
   - The bot could report on trades, or maybe even allow a way to do trades via discord.

**Comment by Mayple7** [comment]
This sounds like a separate bot. The fantasy bot I want to create for the keeper league will be different than this one. I'm not sure if you want fantasy football functionality in the normal discord.

**Comment by DBH1986** [comment]
Its possible some of the functionality might be nice, but agreed that anything keeper league specific might fit better in its own bot
